Add exit code

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -32,11 +32,24 @@ jobs:
 
             - name: Run server
               run: |
-                  npm run dev:standalone &
+                  ((npm run dev:standalone 2>&1 & echo $! > pid.log) | tee server.log) &
                   sleep 40
+                  error_count=$(grep -i error server.log | wc -l)
+                  echo "Errors Found: $error_count"
+                  if [[ $error_count -gt 0 ]]; then
+                    echo "Exiting server"
+                    kill $(<pid.log)
+                    exit 1
+                  fi
 
-            - name: Run Lint, Unit, and Functional Non-Snapshot Tests
+            - name: Lint
               run: |
                   npm run lint
+
+            - name: Unit Tests
+              run: |
                   npm run test
+
+            - name: Functional Non-Snapshot Tests
+              run: |
                   npm run test:func:nosnaps
